---
kind: pipeline
type: docker
name: check

steps:
  - name: gofmt
    image: golang:1.13-buster
    commands:
      - make check-gofmt

  - name: revive
    image: golang:1.13-buster
    commands:
      - go get -u github.com/mgechev/revive
      - make check-revive

---
kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: golang:1.13-buster
    commands:
      - make test

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN

depends_on:
  - check

---
kind: pipeline
type: docker
name: linux-amd64

steps:
  - name: build
    image: golang:1.13-buster
    commands:
      - make build
    environment:
      GOOS: linux
      GOARCH: amd64
      BUILD_OUTPUT: wait4x-linux-amd64

  - name: pre-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      files:
        - wait4x-linux-amd64
      checksum:
        - sha256
      checksum_file: wait4x-linux-amd64.CHECKSUMsum
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"
    depends_on:
      - build

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - wait4x-linux-amd64
      checksum:
        - sha256
      checksum_file: wait4x-linux-amd64.CHECKSUMsum
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*"
        exclude:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"
    depends_on:
      - build

depends_on:
  - test

---
kind: pipeline
type: docker
name: linux-musl-amd64

steps:
  - name: build
    image: golang:1.13-alpine
    commands:
      - apk --update add make git
      - make build
    environment:
      GOOS: linux
      GOARCH: amd64
      BUILD_OUTPUT: wait4x-linux-musl-amd64

  - name: docker
    image: plugins/docker
    settings:
      repo: atkrad/wait4x
      auto_tag: true
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        exclude:
          - pull_request
    depends_on:
      - build

  - name: dockerhub-description
    image: peterevans/dockerhub-description:2.0.0
    environment:
      DOCKERHUB_REPOSITORY: 'atkrad/wait4x'
      DOCKERHUB_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKERHUB_PASSWORD:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        exclude:
          - pull_request
    depends_on:
      - docker

#  - name: quay
#    image: plugins/docker
#    settings:
#      registry: quay.io
#      repo: quay.io/atkrad/wait4x
#      auto_tag: true
#      username:
#        from_secret: QUAY_USERNAME
#      password:
#        from_secret: QUAY_PASSWORD
#    depends_on:
#      - build

  - name: pre-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      files:
        - wait4x-linux-musl-amd64
      checksum:
        - sha256
      checksum_file: wait4x-linux-musl-amd64.CHECKSUMsum
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"
    depends_on:
      - build

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - wait4x-linux-musl-amd64
      checksum:
        - sha256
      checksum_file: wait4x-linux-musl-amd64.CHECKSUMsum
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*"
        exclude:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"
    depends_on:
      - build

depends_on:
  - test

---
kind: pipeline
type: docker
name: darwin-amd64

steps:
  - name: build
    image: golang:1.13-buster
    commands:
      - make build
    environment:
      GOOS: darwin
      GOARCH: amd64
      BUILD_OUTPUT: wait4x-darwin-amd64

  - name: pre-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      files:
        - wait4x-darwin-amd64
      checksum:
        - sha256
      checksum_file: wait4x-darwin-amd64.CHECKSUMsum
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"
    depends_on:
      - build

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - wait4x-darwin-amd64
      checksum:
        - sha256
      checksum_file: wait4x-darwin-amd64.CHECKSUMsum
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*"
        exclude:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"
    depends_on:
      - build

depends_on:
  - test

---
kind: pipeline
type: docker
name: windows-amd64

steps:
  - name: build
    image: golang:1.13-buster
    commands:
      - make build
    environment:
      GOOS: windows
      GOARCH: amd64
      BUILD_OUTPUT: wait4x-windows-amd64

  - name: pre-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      files:
        - wait4x-windows-amd64
      checksum:
        - sha256
      checksum_file: wait4x-windows-amd64.CHECKSUMsum
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"
    depends_on:
      - build

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - wait4x-windows-amd64
      checksum:
        - sha256
      checksum_file: wait4x-windows-amd64.CHECKSUMsum
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*"
        exclude:
          - "refs/tags/*rc*"
          - "refs/tags/*alpha*"
          - "refs/tags/*beta*"
    depends_on:
      - build

depends_on:
  - test
