name: Release

on:
  push:
    branches:
      - 'master'
      - 'release/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            atkrad/wait4x
          ### versioning strategy
          ### push semver tag v3.2.1 on master (default branch)
          # atkrad/wait4x:2.2.0
          # atkrad/wait4x:2.2
          # atkrad/wait4x:2
          # atkrad/wait4x:latest
          ### push semver pre-release tag v3.0.0-beta.1 on master (default branch)
          # atkrad/wait4x:3.0.0-beta.1
          ### push on master (default branch)
          # atkrad/wait4x:edge
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr
            type=edge,branch=master

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build artifacts
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,windows/amd64,windows/arm64,darwin/amd64,darwin/arm64
          push: false
          target: artifact
          outputs: type=local,dest=./dist
          cache-from: type=registry,ref=atkrad/wait4x:edge
          cache-to: type=inline

      - name: Move artifacts
        run: |
          mv ./dist/**/* ./dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wait4x-artifacts
          path: ./dist/*
          if-no-files-found: error

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=atkrad/wait4x:edge
          cache-to: type=inline

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*.tar.gz
            dist/*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
